export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOAD_TOURNAMENTLIST_SUCCESS = "LOAD_TOURNAMENTLIST_SUCCESS";
export const LOAD_TEMPLATELIST_SUCCESS = "LOAD_TEMPLATELIST_SUCCESS";
export const LOAD_TOURNAMENT_SUCCESS = "LOAD_TOURNAMENT_SUCCESS";
export const LOAD_LIGASUMMARY_SUCCESS = "LOAD_LIGASUMMARY_SUCCESS";
export const LOAD_PLAYERLIST_SUCCESS = "LOAD_PLAYERLIST_SUCCESS";
export const CREATE_PLAYER_SUCCESS = "CREATE_PLAYER_SUCCESS";
export const UPDATE_PLAYER_SUCCESS = "UPDATE_PLAYER_SUCCESS";
export const UPDATE_ROUND_SUCCESS = "UPDATE_ROUND_SUCCESS";
export const UPDATE_MATCH_SUCCESS = "UPDATE_MATCH_SUCCESS";
export const CREATE_TOURNAMENT_SUCCESS = "CREATE_TOURNAMENT_SUCCESS";