export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

export const LOAD_TOURNAMENTLIST_SUCCESS = "LOAD_TOURNAMENTLIST_SUCCESS";
export const LOAD_TOURNAMENTLIST_FAILURE = "LOAD_TOURNAMENTLIST_FAILURE";

export const LOAD_TEMPLATELIST_SUCCESS = "LOAD_TEMPLATELIST_SUCCESS";
export const LOAD_TEMPLATELIST_FAILURE = "LOAD_TEMPLATELIST_FAILURE";

export const LOAD_TOURNAMENT_SUCCESS = "LOAD_TOURNAMENT_SUCCESS";
export const LOAD_TOURNAMENT_FAILURE = "LOAD_TOURNAMENT_FAILURE";

export const LOAD_LIGASUMMARY_SUCCESS = "LOAD_LIGASUMMARY_SUCCESS";
export const LOAD_LIGASUMMARY_FAILURE = "LOAD_LIGASUMMARY_FAILURE";

export const LOAD_PLAYERLIST_SUCCESS = "LOAD_PLAYERLIST_SUCCESS";
export const LOAD_PLAYERLIST_FAILURE = "LOAD_PLAYERLIST_FAILURE";

export const UPDATE_ROUND_SUCCESS = "UPDATE_ROUND_SUCCESS";
export const UPDATE_ROUND_FAILURE = "UPDATE_ROUND_FAILURE";

export const UPDATE_MATCH_SUCCESS = "UPDATE_MATCH_SUCCESS";
export const UPDATE_MATCH_FAILURE = "UPDATE_MATCH_FAILURE";
