export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

export const LOAD_TOURNAMENTLIST_SUCCESS = "LOAD_TOURNAMENTLIST_SUCCESS";
export const LOAD_TOURNAMENT_SUCCESS = "LOAD_TOURNAMENT_SUCCESS";
export const LOAD_LIGASUMMARY_SUCCESS = "LOAD_LIGASUMMARY_SUCCESS";
export const UPDATE_ROUND_SUCCESS = "UPDATE_ROUND_SUCCESS";
export const UPDATE_MATCH_SUCCESS = "UPDATE_MATCH_SUCCESS";